import Head from 'next/head'
import Link from 'next/link'
import SimpleEncryption from './apps/simple-encryption.js'


export default function Home() {

  var _view = null;

  _view = SimpleEncryption;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@500&family=Pacifico&family=Roboto:ital,wght@0,500;0,700;1,300&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Cantarell:wght@400;700&family=Inter:wght@400;700;900&family=Ubuntu:wght@400;700&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300;400&display=swap" rel="stylesheet"/>
      </Head>

      
      <_view/>

      
    </>
  )


}
